spring:
  redis:
    host: 192.168.80.150
    port: 6379
    password: 123456
#  dubbo:
#    registry:
#         address: zookeeper://10.0.20.131:2181?backup=10.0.20.131:2181,10.0.20.133:2181,10.0.20.175:2181
#    protocol:
#         name: dubbo
#         port: 20880
#    scan: com.caox.service
#    references: 0
#    timeout: 50000

server:
  port: 9099
#spring:
#  application:
#    name: apolloDeno
app:
  id: 110
# set apollo meta server address, adjust to actual address if necessary
apollo:
  meta: http://10.6.51.112:8080
  bootstrap:
        enabled : true


