spring:
  redis:
    host: 192.168.80.150
    port: 6379
    password: 123456
#  dubbo:
#    registry:
#         address:
#    protocol:
#         name: dubbo
#         port: 20880
#    scan: com.caox.service
#    references: 0
#    timeout: 50000

server:
  port: 9099
#spring:
#  application:
#    name: apolloDeno
app:
  id: 110
# set apollo meta server address, adjust to actual address if necessary
apollo:
  meta:
  bootstrap:
        enabled : true


