#app:
#  id: 113
## set apollo meta server address, adjust to actual address if necessary
#apollo:
#  meta: http://10.0.55.86:8080
#  bootstrap:
#        enabled : true

server:
   port: 8766

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
      registerWithEureka: true

spring:
    application:
       name: consumer-feign

tx-lcn:
   client:
        manager-address: localhost:8070

#ribbon:
#  eureka:
#    enabled: true