package com.caox.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogonRespMsg.proto

public final class LogonRespMsg {
  private LogonRespMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code UserStatus}
   */
  public enum UserStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OFFLINE = 0;</code>
     */
    OFFLINE(0),
    /**
     * <code>ONLINE = 1;</code>
     */
    ONLINE(1),
    ;

    /**
     * <code>OFFLINE = 0;</code>
     */
    public static final int OFFLINE_VALUE = 0;
    /**
     * <code>ONLINE = 1;</code>
     */
    public static final int ONLINE_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static UserStatus valueOf(int value) {
      return forNumber(value);
    }

    public static UserStatus forNumber(int value) {
      switch (value) {
        case 0: return OFFLINE;
        case 1: return ONLINE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserStatus>() {
            public UserStatus findValueByNumber(int number) {
              return UserStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return LogonRespMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final UserStatus[] VALUES = values();

    public static UserStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:UserStatus)
  }

  /**
   * Protobuf enum {@code LoginResult}
   */
  public enum LoginResult
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGON_RESULT_SUCCESS = 0;</code>
     */
    LOGON_RESULT_SUCCESS(0),
    /**
     * <code>LOGON_RESULT_NOTEXIST = 1;</code>
     */
    LOGON_RESULT_NOTEXIST(1),
    /**
     * <code>LOGON_RESULT_ERROR_PASSWD = 2;</code>
     */
    LOGON_RESULT_ERROR_PASSWD(2),
    /**
     * <code>LOGON_RESULT_ALREADY_LOGON = 3;</code>
     */
    LOGON_RESULT_ALREADY_LOGON(3),
    /**
     * <code>LOGON_RESULT_SERVER_ERROR = 4;</code>
     */
    LOGON_RESULT_SERVER_ERROR(4),
    ;

    /**
     * <code>LOGON_RESULT_SUCCESS = 0;</code>
     */
    public static final int LOGON_RESULT_SUCCESS_VALUE = 0;
    /**
     * <code>LOGON_RESULT_NOTEXIST = 1;</code>
     */
    public static final int LOGON_RESULT_NOTEXIST_VALUE = 1;
    /**
     * <code>LOGON_RESULT_ERROR_PASSWD = 2;</code>
     */
    public static final int LOGON_RESULT_ERROR_PASSWD_VALUE = 2;
    /**
     * <code>LOGON_RESULT_ALREADY_LOGON = 3;</code>
     */
    public static final int LOGON_RESULT_ALREADY_LOGON_VALUE = 3;
    /**
     * <code>LOGON_RESULT_SERVER_ERROR = 4;</code>
     */
    public static final int LOGON_RESULT_SERVER_ERROR_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static LoginResult valueOf(int value) {
      return forNumber(value);
    }

    public static LoginResult forNumber(int value) {
      switch (value) {
        case 0: return LOGON_RESULT_SUCCESS;
        case 1: return LOGON_RESULT_NOTEXIST;
        case 2: return LOGON_RESULT_ERROR_PASSWD;
        case 3: return LOGON_RESULT_ALREADY_LOGON;
        case 4: return LOGON_RESULT_SERVER_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LoginResult>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LoginResult> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LoginResult>() {
            public LoginResult findValueByNumber(int number) {
              return LoginResult.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return LogonRespMsg.getDescriptor().getEnumTypes().get(1);
    }

    private static final LoginResult[] VALUES = values();

    public static LoginResult valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LoginResult(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:LoginResult)
  }

  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 acctID = 1;</code>
     */
    boolean hasAcctID();
    /**
     * <code>required int64 acctID = 1;</code>
     */
    long getAcctID();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .UserStatus status = 3;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .UserStatus status = 3;</code>
     */
    UserStatus getStatus();
  }
  /**
   * Protobuf type {@code UserInfo}
   */
  public  static final class UserInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:UserInfo)
      UserInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserInfo() {
      acctID_ = 0L;
      name_ = "";
      status_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              acctID_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              UserStatus value = UserStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                status_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LogonRespMsg.internal_static_UserInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LogonRespMsg.internal_static_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserInfo.class, Builder.class);
    }

    private int bitField0_;
    public static final int ACCTID_FIELD_NUMBER = 1;
    private long acctID_;
    /**
     * <code>required int64 acctID = 1;</code>
     */
    public boolean hasAcctID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 acctID = 1;</code>
     */
    public long getAcctID() {
      return acctID_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>required .UserStatus status = 3;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .UserStatus status = 3;</code>
     */
    public UserStatus getStatus() {
      @SuppressWarnings("deprecation")
      UserStatus result = UserStatus.valueOf(status_);
      return result == null ? UserStatus.OFFLINE : result;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAcctID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, acctID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, status_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, acctID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserInfo)) {
        return super.equals(obj);
      }
      UserInfo other = (UserInfo) obj;

      boolean result = true;
      result = result && (hasAcctID() == other.hasAcctID());
      if (hasAcctID()) {
        result = result && (getAcctID()
            == other.getAcctID());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasStatus() == other.hasStatus());
      if (hasStatus()) {
        result = result && status_ == other.status_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAcctID()) {
        hash = (37 * hash) + ACCTID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAcctID());
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserInfo)
        UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LogonRespMsg.internal_static_UserInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LogonRespMsg.internal_static_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserInfo.class, Builder.class);
      }

      // Construct using LogonRespMsg.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        acctID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LogonRespMsg.internal_static_UserInfo_descriptor;
      }

      @Override
      public UserInfo getDefaultInstanceForType() {
        return UserInfo.getDefaultInstance();
      }

      @Override
      public UserInfo build() {
        UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public UserInfo buildPartial() {
        UserInfo result = new UserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.acctID_ = acctID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserInfo) {
          return mergeFrom((UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserInfo other) {
        if (other == UserInfo.getDefaultInstance()) return this;
        if (other.hasAcctID()) {
          setAcctID(other.getAcctID());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasAcctID()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasStatus()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UserInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long acctID_ ;
      /**
       * <code>required int64 acctID = 1;</code>
       */
      public boolean hasAcctID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 acctID = 1;</code>
       */
      public long getAcctID() {
        return acctID_;
      }
      /**
       * <code>required int64 acctID = 1;</code>
       */
      public Builder setAcctID(long value) {
        bitField0_ |= 0x00000001;
        acctID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 acctID = 1;</code>
       */
      public Builder clearAcctID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        acctID_ = 0L;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>required .UserStatus status = 3;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .UserStatus status = 3;</code>
       */
      public UserStatus getStatus() {
        @SuppressWarnings("deprecation")
        UserStatus result = UserStatus.valueOf(status_);
        return result == null ? UserStatus.OFFLINE : result;
      }
      /**
       * <code>required .UserStatus status = 3;</code>
       */
      public Builder setStatus(UserStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .UserStatus status = 3;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UserInfo)
    }

    // @@protoc_insertion_point(class_scope:UserInfo)
    private static final UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserInfo();
    }

    public static UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<UserInfo>
        PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
      @Override
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public UserInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LogonRespMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LogonRespMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .LoginResult logonResult = 1;</code>
     */
    boolean hasLogonResult();
    /**
     * <code>required .LoginResult logonResult = 1;</code>
     */
    LoginResult getLogonResult();

    /**
     * <pre>
     * userInfo (����)
     * </pre>
     *
     * <code>repeated .UserInfo userInfos = 2;</code>
     */
    java.util.List<UserInfo>
        getUserInfosList();
    /**
     * <pre>
     * userInfo (����)
     * </pre>
     *
     * <code>repeated .UserInfo userInfos = 2;</code>
     */
    UserInfo getUserInfos(int index);
    /**
     * <pre>
     * userInfo (����)
     * </pre>
     *
     * <code>repeated .UserInfo userInfos = 2;</code>
     */
    int getUserInfosCount();
    /**
     * <pre>
     * userInfo (����)
     * </pre>
     *
     * <code>repeated .UserInfo userInfos = 2;</code>
     */
    java.util.List<? extends UserInfoOrBuilder>
        getUserInfosOrBuilderList();
    /**
     * <pre>
     * userInfo (����)
     * </pre>
     *
     * <code>repeated .UserInfo userInfos = 2;</code>
     */
    UserInfoOrBuilder getUserInfosOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code LogonRespMessage}
   */
  public  static final class LogonRespMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LogonRespMessage)
      LogonRespMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogonRespMessage.newBuilder() to construct.
    private LogonRespMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogonRespMessage() {
      logonResult_ = 0;
      userInfos_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogonRespMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              LoginResult value = LoginResult.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                logonResult_ = rawValue;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                userInfos_ = new java.util.ArrayList<UserInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              userInfos_.add(
                  input.readMessage(UserInfo.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          userInfos_ = java.util.Collections.unmodifiableList(userInfos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LogonRespMsg.internal_static_LogonRespMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LogonRespMsg.internal_static_LogonRespMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LogonRespMessage.class, Builder.class);
    }

    private int bitField0_;
    public static final int LOGONRESULT_FIELD_NUMBER = 1;
    private int logonResult_;
    /**
     * <code>required .LoginResult logonResult = 1;</code>
     */
    public boolean hasLogonResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .LoginResult logonResult = 1;</code>
     */
    public LoginResult getLogonResult() {
      @SuppressWarnings("deprecation")
      LoginResult result = LoginResult.valueOf(logonResult_);
      return result == null ? LoginResult.LOGON_RESULT_SUCCESS : result;
    }

    public static final int USERINFOS_FIELD_NUMBER = 2;
    private java.util.List<UserInfo> userInfos_;
    /**
     * <pre>
     * userInfo (����)
     * </pre>
     *
     * <code>repeated .UserInfo userInfos = 2;</code>
     */
    public java.util.List<UserInfo> getUserInfosList() {
      return userInfos_;
    }
    /**
     * <pre>
     * userInfo (����)
     * </pre>
     *
     * <code>repeated .UserInfo userInfos = 2;</code>
     */
    public java.util.List<? extends UserInfoOrBuilder>
        getUserInfosOrBuilderList() {
      return userInfos_;
    }
    /**
     * <pre>
     * userInfo (����)
     * </pre>
     *
     * <code>repeated .UserInfo userInfos = 2;</code>
     */
    public int getUserInfosCount() {
      return userInfos_.size();
    }
    /**
     * <pre>
     * userInfo (����)
     * </pre>
     *
     * <code>repeated .UserInfo userInfos = 2;</code>
     */
    public UserInfo getUserInfos(int index) {
      return userInfos_.get(index);
    }
    /**
     * <pre>
     * userInfo (����)
     * </pre>
     *
     * <code>repeated .UserInfo userInfos = 2;</code>
     */
    public UserInfoOrBuilder getUserInfosOrBuilder(
        int index) {
      return userInfos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLogonResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getUserInfosCount(); i++) {
        if (!getUserInfos(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, logonResult_);
      }
      for (int i = 0; i < userInfos_.size(); i++) {
        output.writeMessage(2, userInfos_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, logonResult_);
      }
      for (int i = 0; i < userInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, userInfos_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LogonRespMessage)) {
        return super.equals(obj);
      }
      LogonRespMessage other = (LogonRespMessage) obj;

      boolean result = true;
      result = result && (hasLogonResult() == other.hasLogonResult());
      if (hasLogonResult()) {
        result = result && logonResult_ == other.logonResult_;
      }
      result = result && getUserInfosList()
          .equals(other.getUserInfosList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLogonResult()) {
        hash = (37 * hash) + LOGONRESULT_FIELD_NUMBER;
        hash = (53 * hash) + logonResult_;
      }
      if (getUserInfosCount() > 0) {
        hash = (37 * hash) + USERINFOS_FIELD_NUMBER;
        hash = (53 * hash) + getUserInfosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LogonRespMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogonRespMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogonRespMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogonRespMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogonRespMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogonRespMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogonRespMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogonRespMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogonRespMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LogonRespMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogonRespMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogonRespMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LogonRespMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LogonRespMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LogonRespMessage)
        LogonRespMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LogonRespMsg.internal_static_LogonRespMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LogonRespMsg.internal_static_LogonRespMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LogonRespMessage.class, Builder.class);
      }

      // Construct using LogonRespMsg.LogonRespMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserInfosFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        logonResult_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (userInfosBuilder_ == null) {
          userInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          userInfosBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LogonRespMsg.internal_static_LogonRespMessage_descriptor;
      }

      @Override
      public LogonRespMessage getDefaultInstanceForType() {
        return LogonRespMessage.getDefaultInstance();
      }

      @Override
      public LogonRespMessage build() {
        LogonRespMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public LogonRespMessage buildPartial() {
        LogonRespMessage result = new LogonRespMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.logonResult_ = logonResult_;
        if (userInfosBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            userInfos_ = java.util.Collections.unmodifiableList(userInfos_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.userInfos_ = userInfos_;
        } else {
          result.userInfos_ = userInfosBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LogonRespMessage) {
          return mergeFrom((LogonRespMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LogonRespMessage other) {
        if (other == LogonRespMessage.getDefaultInstance()) return this;
        if (other.hasLogonResult()) {
          setLogonResult(other.getLogonResult());
        }
        if (userInfosBuilder_ == null) {
          if (!other.userInfos_.isEmpty()) {
            if (userInfos_.isEmpty()) {
              userInfos_ = other.userInfos_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureUserInfosIsMutable();
              userInfos_.addAll(other.userInfos_);
            }
            onChanged();
          }
        } else {
          if (!other.userInfos_.isEmpty()) {
            if (userInfosBuilder_.isEmpty()) {
              userInfosBuilder_.dispose();
              userInfosBuilder_ = null;
              userInfos_ = other.userInfos_;
              bitField0_ = (bitField0_ & ~0x00000002);
              userInfosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserInfosFieldBuilder() : null;
            } else {
              userInfosBuilder_.addAllMessages(other.userInfos_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasLogonResult()) {
          return false;
        }
        for (int i = 0; i < getUserInfosCount(); i++) {
          if (!getUserInfos(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LogonRespMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LogonRespMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int logonResult_ = 0;
      /**
       * <code>required .LoginResult logonResult = 1;</code>
       */
      public boolean hasLogonResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .LoginResult logonResult = 1;</code>
       */
      public LoginResult getLogonResult() {
        @SuppressWarnings("deprecation")
        LoginResult result = LoginResult.valueOf(logonResult_);
        return result == null ? LoginResult.LOGON_RESULT_SUCCESS : result;
      }
      /**
       * <code>required .LoginResult logonResult = 1;</code>
       */
      public Builder setLogonResult(LoginResult value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        logonResult_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .LoginResult logonResult = 1;</code>
       */
      public Builder clearLogonResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        logonResult_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<UserInfo> userInfos_ =
        java.util.Collections.emptyList();
      private void ensureUserInfosIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          userInfos_ = new java.util.ArrayList<UserInfo>(userInfos_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          UserInfo, UserInfo.Builder, UserInfoOrBuilder> userInfosBuilder_;

      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public java.util.List<UserInfo> getUserInfosList() {
        if (userInfosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(userInfos_);
        } else {
          return userInfosBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public int getUserInfosCount() {
        if (userInfosBuilder_ == null) {
          return userInfos_.size();
        } else {
          return userInfosBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public UserInfo getUserInfos(int index) {
        if (userInfosBuilder_ == null) {
          return userInfos_.get(index);
        } else {
          return userInfosBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public Builder setUserInfos(
          int index, UserInfo value) {
        if (userInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserInfosIsMutable();
          userInfos_.set(index, value);
          onChanged();
        } else {
          userInfosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public Builder setUserInfos(
          int index, UserInfo.Builder builderForValue) {
        if (userInfosBuilder_ == null) {
          ensureUserInfosIsMutable();
          userInfos_.set(index, builderForValue.build());
          onChanged();
        } else {
          userInfosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public Builder addUserInfos(UserInfo value) {
        if (userInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserInfosIsMutable();
          userInfos_.add(value);
          onChanged();
        } else {
          userInfosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public Builder addUserInfos(
          int index, UserInfo value) {
        if (userInfosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserInfosIsMutable();
          userInfos_.add(index, value);
          onChanged();
        } else {
          userInfosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public Builder addUserInfos(
          UserInfo.Builder builderForValue) {
        if (userInfosBuilder_ == null) {
          ensureUserInfosIsMutable();
          userInfos_.add(builderForValue.build());
          onChanged();
        } else {
          userInfosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public Builder addUserInfos(
          int index, UserInfo.Builder builderForValue) {
        if (userInfosBuilder_ == null) {
          ensureUserInfosIsMutable();
          userInfos_.add(index, builderForValue.build());
          onChanged();
        } else {
          userInfosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public Builder addAllUserInfos(
          Iterable<? extends UserInfo> values) {
        if (userInfosBuilder_ == null) {
          ensureUserInfosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, userInfos_);
          onChanged();
        } else {
          userInfosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public Builder clearUserInfos() {
        if (userInfosBuilder_ == null) {
          userInfos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          userInfosBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public Builder removeUserInfos(int index) {
        if (userInfosBuilder_ == null) {
          ensureUserInfosIsMutable();
          userInfos_.remove(index);
          onChanged();
        } else {
          userInfosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public UserInfo.Builder getUserInfosBuilder(
          int index) {
        return getUserInfosFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public UserInfoOrBuilder getUserInfosOrBuilder(
          int index) {
        if (userInfosBuilder_ == null) {
          return userInfos_.get(index);  } else {
          return userInfosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public java.util.List<? extends UserInfoOrBuilder>
           getUserInfosOrBuilderList() {
        if (userInfosBuilder_ != null) {
          return userInfosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(userInfos_);
        }
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public UserInfo.Builder addUserInfosBuilder() {
        return getUserInfosFieldBuilder().addBuilder(
            UserInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public UserInfo.Builder addUserInfosBuilder(
          int index) {
        return getUserInfosFieldBuilder().addBuilder(
            index, UserInfo.getDefaultInstance());
      }
      /**
       * <pre>
       * userInfo (����)
       * </pre>
       *
       * <code>repeated .UserInfo userInfos = 2;</code>
       */
      public java.util.List<UserInfo.Builder>
           getUserInfosBuilderList() {
        return getUserInfosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          UserInfo, UserInfo.Builder, UserInfoOrBuilder>
          getUserInfosFieldBuilder() {
        if (userInfosBuilder_ == null) {
          userInfosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              UserInfo, UserInfo.Builder, UserInfoOrBuilder>(
                  userInfos_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          userInfos_ = null;
        }
        return userInfosBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LogonRespMessage)
    }

    // @@protoc_insertion_point(class_scope:LogonRespMessage)
    private static final LogonRespMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LogonRespMessage();
    }

    public static LogonRespMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<LogonRespMessage>
        PARSER = new com.google.protobuf.AbstractParser<LogonRespMessage>() {
      @Override
      public LogonRespMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogonRespMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogonRespMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LogonRespMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public LogonRespMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogonRespMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogonRespMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022LogonRespMsg.proto\"E\n\010UserInfo\022\016\n\006acct" +
      "ID\030\001 \002(\003\022\014\n\004name\030\002 \002(\t\022\033\n\006status\030\003 \002(\0162\013" +
      ".UserStatus\"S\n\020LogonRespMessage\022!\n\013logon" +
      "Result\030\001 \002(\0162\014.LoginResult\022\034\n\tuserInfos\030" +
      "\002 \003(\0132\t.UserInfo*%\n\nUserStatus\022\013\n\007OFFLIN" +
      "E\020\000\022\n\n\006ONLINE\020\001*\240\001\n\013LoginResult\022\030\n\024LOGON" +
      "_RESULT_SUCCESS\020\000\022\031\n\025LOGON_RESULT_NOTEXI" +
      "ST\020\001\022\035\n\031LOGON_RESULT_ERROR_PASSWD\020\002\022\036\n\032L" +
      "OGON_RESULT_ALREADY_LOGON\020\003\022\035\n\031LOGON_RES" +
      "ULT_SERVER_ERROR\020\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserInfo_descriptor,
        new String[] { "AcctID", "Name", "Status", });
    internal_static_LogonRespMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LogonRespMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogonRespMessage_descriptor,
        new String[] { "LogonResult", "UserInfos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
